/**
 * This script takes the outputed types from `prisma-kysely-generator`
 * and puts them + instantiates the Kysely instance into `~/server/db.ts`
 */

import { readFile, rm, writeFile } from "fs/promises";
import path from "path";

import { format, resolveConfig } from "prettier";

const generatedFile = path.join(process.cwd(), "types.ts");
const outputFile = path.join(process.cwd(), "index.ts");

(async () => {
  const prettierConfig = await resolveConfig(".prettierrc.js");

  const dbTypes = await readFile(generatedFile, "utf-8");

  const output = `// Generated by prisma/post-generate.ts

import { Kysely } from "kysely";
import { PlanetScaleDialect } from "kysely-planetscale";
import { nanoid } from "nanoid";

${dbTypes}

export const db = new Kysely<DB>({
  dialect: new PlanetScaleDialect({
    url: process.env.DATABASE_URL,
  }),
});

export const genId = nanoid;
`;

  const formatted = format(output, {
    ...prettierConfig,
    parser: "typescript",
  });
  await writeFile(outputFile, formatted);
  await rm(path.join(process.cwd(), "types.ts"));
})().catch((e) => {
  console.error(e);
  process.exit(1);
});
